// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fullproto.proto
// Protobuf Java Version: 4.26.0

package ru.annikonenkov.myconversation;

public final class ExampleProto {

  private ExampleProto() {
  }

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "", ExampleProto.class.getName());
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor internal_static_com_example_grpc_Request_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_example_grpc_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor internal_static_com_example_grpc_Response_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_example_grpc_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor internal_static_com_example_grpc_StreamRequest_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_example_grpc_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor internal_static_com_example_grpc_StreamResponse_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_example_grpc_StreamResponse_fieldAccessorTable;

  //
  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {"\n\017fullproto.proto\022\020com.example.grpc\"&\n\007R"
        + "equest\022\017\n\007message\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\"0\n\010R"
        + "esponse\022\016\n\006result\030\001 \001(\t\022\024\n\014processed_id\030"
        + "\002 \001(\005\"\035\n\rStreamRequest\022\014\n\004data\030\001 \001(\t\";\n\016"
        + "StreamResponse\022\026\n\016processed_data\030\001 \001(\t\022\021"
        + "\n\ttimestamp\030\002 \001(\0032\250\003\n\016ExampleService\022D\n\t"
        + "UnarySync\022\031.com.example.grpc.Request\032\032.c"
        + "om.example.grpc.Response\"\000\022E\n\nUnaryAsync"
        + "\022\031.com.example.grpc.Request\032\032.com.exampl"
        + "e.grpc.Response\"\000\022R\n\017ServerStreaming\022\031.c"
        + "om.example.grpc.Request\032 .com.example.gr"
        + "pc.StreamResponse\"\0000\001\022R\n\017ClientStreaming"
        + "\022\037.com.example.grpc.StreamRequest\032\032.com."
        + "example.grpc.Response\"\000(\001\022a\n\026Bidirection"
        + "alStreaming\022\037.com.example.grpc.StreamReq"
        + "uest\032 .com.example.grpc.StreamResponse\"\000"
        + "(\0010\001B0\n\036ru.annikonenkov.myconversationB\014" + "ExampleProtoP\001b\006proto3"};
    descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[]{});
    internal_static_com_example_grpc_Request_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_Request_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_com_example_grpc_Request_descriptor, new java.lang.String[]{"Message", "Id",});
    internal_static_com_example_grpc_Response_descriptor = getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_Response_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_com_example_grpc_Response_descriptor, new java.lang.String[]{"Result", "ProcessedId",});
    internal_static_com_example_grpc_StreamRequest_descriptor = getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_grpc_StreamRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_com_example_grpc_StreamRequest_descriptor, new java.lang.String[]{"Data",});
    internal_static_com_example_grpc_StreamResponse_descriptor = getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_grpc_StreamResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_com_example_grpc_StreamResponse_descriptor, new java.lang.String[]{"ProcessedData", "Timestamp",});
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
