// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fullproto.proto

// Protobuf Java Version: 4.26.0
package ru.annikonenkov.myconversation;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   *
   * @return The message.
   */
  java.lang.String getMessage();

  /**
   * <code>string message = 1;</code>
   *
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString getMessageBytes();

  /**
   * <code>int32 id = 2;</code>
   *
   * @return The id.
   */
  int getId();
}
