// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fullproto.proto

// Protobuf Java Version: 4.26.0
package ru.annikonenkov.myconversation;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   *
   * @return The result.
   */
  java.lang.String getResult();

  /**
   * <code>string result = 1;</code>
   *
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString getResultBytes();

  /**
   * <code>int32 processed_id = 2;</code>
   *
   * @return The processedId.
   */
  int getProcessedId();
}
