// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fullproto.proto

// Protobuf Java Version: 4.26.0
package ru.annikonenkov.myconversation;

/**
 * Protobuf type {@code com.example.grpc.Response}
 */
public final class Response extends com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.Response)
    ResponseOrBuilder {

  private static final long serialVersionUID = 0L;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "", Response.class.getName());
  }

  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }

  private Response() {
    result_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return ru.annikonenkov.myconversation.ExampleProto.internal_static_com_example_grpc_Response_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
    return ru.annikonenkov.myconversation.ExampleProto.internal_static_com_example_grpc_Response_fieldAccessorTable.ensureFieldAccessorsInitialized(
        ru.annikonenkov.myconversation.Response.class,
        ru.annikonenkov.myconversation.Response.Builder.class);
  }

  public static final int RESULT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object result_ = "";

  /**
   * <code>string result = 1;</code>
   *
   * @return The result.
   */
  @java.lang.Override
  public java.lang.String getResult() {
    java.lang.Object ref = result_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      result_ = s;
      return s;
    }
  }

  /**
   * <code>string result = 1;</code>
   *
   * @return The bytes for result.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getResultBytes() {
    java.lang.Object ref = result_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      result_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROCESSED_ID_FIELD_NUMBER = 2;
  private int processedId_ = 0;

  /**
   * <code>int32 processed_id = 2;</code>
   *
   * @return The processedId.
   */
  @java.lang.Override
  public int getProcessedId() {
    return processedId_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) {
      return true;
    }
    if (isInitialized == 0) {
      return false;
    }

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(result_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, result_);
    }
    if (processedId_ != 0) {
      output.writeInt32(2, processedId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) {
      return size;
    }

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(result_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, result_);
    }
    if (processedId_ != 0) {
      size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, processedId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof ru.annikonenkov.myconversation.Response)) {
      return super.equals(obj);
    }
    ru.annikonenkov.myconversation.Response other = (ru.annikonenkov.myconversation.Response) obj;

    if (!getResult().equals(other.getResult())) {
      return false;
    }
    if (getProcessedId() != other.getProcessedId()) {
      return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) {
      return false;
    }
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + getResult().hashCode();
    hash = (37 * hash) + PROCESSED_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProcessedId();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.annikonenkov.myconversation.Response parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static ru.annikonenkov.myconversation.Response parseFrom(java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static ru.annikonenkov.myconversation.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static ru.annikonenkov.myconversation.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static ru.annikonenkov.myconversation.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static ru.annikonenkov.myconversation.Response parseFrom(byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static ru.annikonenkov.myconversation.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static ru.annikonenkov.myconversation.Response parseFrom(java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static ru.annikonenkov.myconversation.Response parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
  }

  public static ru.annikonenkov.myconversation.Response parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static ru.annikonenkov.myconversation.Response parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static ru.annikonenkov.myconversation.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(ru.annikonenkov.myconversation.Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code com.example.grpc.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.Response)
      ru.annikonenkov.myconversation.ResponseOrBuilder {

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return ru.annikonenkov.myconversation.ExampleProto.internal_static_com_example_grpc_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
      return ru.annikonenkov.myconversation.ExampleProto.internal_static_com_example_grpc_Response_fieldAccessorTable.ensureFieldAccessorsInitialized(
          ru.annikonenkov.myconversation.Response.class,
          ru.annikonenkov.myconversation.Response.Builder.class);
    }

    // Construct using ru.annikonenkov.myconversation.Response.newBuilder()
    private Builder() {

    }

    private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      result_ = "";
      processedId_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return ru.annikonenkov.myconversation.ExampleProto.internal_static_com_example_grpc_Response_descriptor;
    }

    @java.lang.Override
    public ru.annikonenkov.myconversation.Response getDefaultInstanceForType() {
      return ru.annikonenkov.myconversation.Response.getDefaultInstance();
    }

    @java.lang.Override
    public ru.annikonenkov.myconversation.Response build() {
      ru.annikonenkov.myconversation.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.annikonenkov.myconversation.Response buildPartial() {
      ru.annikonenkov.myconversation.Response result = new ru.annikonenkov.myconversation.Response(
          this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(ru.annikonenkov.myconversation.Response result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.result_ = result_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.processedId_ = processedId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.annikonenkov.myconversation.Response) {
        return mergeFrom((ru.annikonenkov.myconversation.Response) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.annikonenkov.myconversation.Response other) {
      if (other == ru.annikonenkov.myconversation.Response.getDefaultInstance()) {
        return this;
      }
      if (!other.getResult().isEmpty()) {
        result_ = other.result_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getProcessedId() != 0) {
        setProcessedId(other.getProcessedId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              result_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              processedId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private java.lang.Object result_ = "";

    /**
     * <code>string result = 1;</code>
     *
     * @return The result.
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        result_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string result = 1;</code>
     *
     * @return The bytes for result.
     */
    public com.google.protobuf.ByteString getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string result = 1;</code>
     *
     * @param value The result to set.
     * @return This builder for chaining.
     */
    public Builder setResult(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      result_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /**
     * <code>string result = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearResult() {
      result_ = getDefaultInstance().getResult();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    /**
     * <code>string result = 1;</code>
     *
     * @param value The bytes for result to set.
     * @return This builder for chaining.
     */
    public Builder setResultBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      result_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int processedId_;

    /**
     * <code>int32 processed_id = 2;</code>
     *
     * @return The processedId.
     */
    @java.lang.Override
    public int getProcessedId() {
      return processedId_;
    }

    /**
     * <code>int32 processed_id = 2;</code>
     *
     * @param value The processedId to set.
     * @return This builder for chaining.
     */
    public Builder setProcessedId(int value) {

      processedId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    /**
     * <code>int32 processed_id = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearProcessedId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      processedId_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.example.grpc.Response)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.Response)
  private static final ru.annikonenkov.myconversation.Response DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new ru.annikonenkov.myconversation.Response();
  }

  public static ru.annikonenkov.myconversation.Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response> PARSER = new com.google.protobuf.AbstractParser<Response>() {
    @java.lang.Override
    public Response parsePartialFrom(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(
            builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.annikonenkov.myconversation.Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

