// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fullproto.proto

// Protobuf Java Version: 4.26.0
package ru.annikonenkov.myconversation;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 1;</code>
   *
   * @return The data.
   */
  java.lang.String getData();

  /**
   * <code>string data = 1;</code>
   *
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString getDataBytes();
}
