// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fullproto.proto

// Protobuf Java Version: 4.26.0
package ru.annikonenkov.myconversation;

/**
 * Protobuf type {@code com.example.grpc.StreamResponse}
 */
public final class StreamResponse extends com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.StreamResponse)
    StreamResponseOrBuilder {

  private static final long serialVersionUID = 0L;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "", StreamResponse.class.getName());
  }

  // Use StreamResponse.newBuilder() to construct.
  private StreamResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }

  private StreamResponse() {
    processedData_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return ru.annikonenkov.myconversation.ExampleProto.internal_static_com_example_grpc_StreamResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
    return ru.annikonenkov.myconversation.ExampleProto.internal_static_com_example_grpc_StreamResponse_fieldAccessorTable.ensureFieldAccessorsInitialized(
        ru.annikonenkov.myconversation.StreamResponse.class,
        ru.annikonenkov.myconversation.StreamResponse.Builder.class);
  }

  public static final int PROCESSED_DATA_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object processedData_ = "";

  /**
   * <code>string processed_data = 1;</code>
   *
   * @return The processedData.
   */
  @java.lang.Override
  public java.lang.String getProcessedData() {
    java.lang.Object ref = processedData_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      processedData_ = s;
      return s;
    }
  }

  /**
   * <code>string processed_data = 1;</code>
   *
   * @return The bytes for processedData.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getProcessedDataBytes() {
    java.lang.Object ref = processedData_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      processedData_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_ = 0L;

  /**
   * <code>int64 timestamp = 2;</code>
   *
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) {
      return true;
    }
    if (isInitialized == 0) {
      return false;
    }

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(processedData_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, processedData_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(2, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) {
      return size;
    }

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(processedData_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, processedData_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream.computeInt64Size(2, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof ru.annikonenkov.myconversation.StreamResponse)) {
      return super.equals(obj);
    }
    ru.annikonenkov.myconversation.StreamResponse other = (ru.annikonenkov.myconversation.StreamResponse) obj;

    if (!getProcessedData().equals(other.getProcessedData())) {
      return false;
    }
    if (getTimestamp() != other.getTimestamp()) {
      return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) {
      return false;
    }
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROCESSED_DATA_FIELD_NUMBER;
    hash = (53 * hash) + getProcessedData().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.annikonenkov.myconversation.StreamResponse parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static ru.annikonenkov.myconversation.StreamResponse parseFrom(java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static ru.annikonenkov.myconversation.StreamResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static ru.annikonenkov.myconversation.StreamResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static ru.annikonenkov.myconversation.StreamResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static ru.annikonenkov.myconversation.StreamResponse parseFrom(byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static ru.annikonenkov.myconversation.StreamResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static ru.annikonenkov.myconversation.StreamResponse parseFrom(java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static ru.annikonenkov.myconversation.StreamResponse parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
  }

  public static ru.annikonenkov.myconversation.StreamResponse parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static ru.annikonenkov.myconversation.StreamResponse parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static ru.annikonenkov.myconversation.StreamResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(ru.annikonenkov.myconversation.StreamResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code com.example.grpc.StreamResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.StreamResponse)
      ru.annikonenkov.myconversation.StreamResponseOrBuilder {

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return ru.annikonenkov.myconversation.ExampleProto.internal_static_com_example_grpc_StreamResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
      return ru.annikonenkov.myconversation.ExampleProto.internal_static_com_example_grpc_StreamResponse_fieldAccessorTable.ensureFieldAccessorsInitialized(
          ru.annikonenkov.myconversation.StreamResponse.class,
          ru.annikonenkov.myconversation.StreamResponse.Builder.class);
    }

    // Construct using ru.annikonenkov.myconversation.StreamResponse.newBuilder()
    private Builder() {

    }

    private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      processedData_ = "";
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return ru.annikonenkov.myconversation.ExampleProto.internal_static_com_example_grpc_StreamResponse_descriptor;
    }

    @java.lang.Override
    public ru.annikonenkov.myconversation.StreamResponse getDefaultInstanceForType() {
      return ru.annikonenkov.myconversation.StreamResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ru.annikonenkov.myconversation.StreamResponse build() {
      ru.annikonenkov.myconversation.StreamResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.annikonenkov.myconversation.StreamResponse buildPartial() {
      ru.annikonenkov.myconversation.StreamResponse result = new ru.annikonenkov.myconversation.StreamResponse(
          this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(ru.annikonenkov.myconversation.StreamResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.processedData_ = processedData_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.annikonenkov.myconversation.StreamResponse) {
        return mergeFrom((ru.annikonenkov.myconversation.StreamResponse) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.annikonenkov.myconversation.StreamResponse other) {
      if (other == ru.annikonenkov.myconversation.StreamResponse.getDefaultInstance()) {
        return this;
      }
      if (!other.getProcessedData().isEmpty()) {
        processedData_ = other.processedData_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              processedData_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private java.lang.Object processedData_ = "";

    /**
     * <code>string processed_data = 1;</code>
     *
     * @return The processedData.
     */
    public java.lang.String getProcessedData() {
      java.lang.Object ref = processedData_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processedData_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string processed_data = 1;</code>
     *
     * @return The bytes for processedData.
     */
    public com.google.protobuf.ByteString getProcessedDataBytes() {
      java.lang.Object ref = processedData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        processedData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string processed_data = 1;</code>
     *
     * @param value The processedData to set.
     * @return This builder for chaining.
     */
    public Builder setProcessedData(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      processedData_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /**
     * <code>string processed_data = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearProcessedData() {
      processedData_ = getDefaultInstance().getProcessedData();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    /**
     * <code>string processed_data = 1;</code>
     *
     * @param value The bytes for processedData to set.
     * @return This builder for chaining.
     */
    public Builder setProcessedDataBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      processedData_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long timestamp_;

    /**
     * <code>int64 timestamp = 2;</code>
     *
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    /**
     * <code>int64 timestamp = 2;</code>
     *
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    /**
     * <code>int64 timestamp = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.example.grpc.StreamResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.StreamResponse)
  private static final ru.annikonenkov.myconversation.StreamResponse DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new ru.annikonenkov.myconversation.StreamResponse();
  }

  public static ru.annikonenkov.myconversation.StreamResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamResponse> PARSER = new com.google.protobuf.AbstractParser<StreamResponse>() {
    @java.lang.Override
    public StreamResponse parsePartialFrom(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(
            builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StreamResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.annikonenkov.myconversation.StreamResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

