// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fullproto.proto

// Protobuf Java Version: 4.26.0
package ru.annikonenkov.myconversation;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string processed_data = 1;</code>
   *
   * @return The processedData.
   */
  java.lang.String getProcessedData();

  /**
   * <code>string processed_data = 1;</code>
   *
   * @return The bytes for processedData.
   */
  com.google.protobuf.ByteString getProcessedDataBytes();

  /**
   * <code>int64 timestamp = 2;</code>
   *
   * @return The timestamp.
   */
  long getTimestamp();
}
